### ISSUE TITLE
Add country to the list of UNICEF’s National Committee countries

### ISSUE THREAD

**Issue by malluQueiroz** [rapidpro/ureport#1213]
Hi!

We have received a request from UNICEF Slovenia for the country name "Slovenija" to be added to the list of UNICEF’s National Committee countries on https://ureport.in/

![image (29)](https://github.com/rapidpro/ureport/assets/170629811/bd42a836-b7f1-47da-9687-d92a12f5ac7b)

**Comment by norkans7** [comment]
I found the issue was a type and fixed that in https://github.com/rapidpro/ureport/commit/ade40dbd9252809f2156580ea71fb7bd65338deb
