### ISSUE TITLE
Correction of country name from Macedona to North Macedonia

### ISSUE THREAD

**Issue by malluQueiroz** [rapidpro/ureport#1224]
Unicef ​​members requested that the country's name be corrected from Macedona to North Macedonia in the https://ureport.in/ list, this country is part of the Europe and Central Asia category, can this correction be made?
![2024-07-09_09-32](https://github.com/rapidpro/ureport/assets/170629811/6ed51f63-42a4-428b-98c8-c684511c8a61)

**Comment by norkans7** [comment]
Already fixed in https://github.com/rapidpro/ureport/commit/8eb335db817f39447c54ad8ec18b104b5fc613a1
