### ISSUE TITLE
Twitter profile widget

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/ureport#190]
Twitter made changes in the way to get the widget's user profile timeline.
You are now directing the user to the https://publish.twitter.com link and generating an embed code like `<a class="twitter-timeline" href="https://twitter.com/TwitterDev">Tweets by TwitterDev</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>`.
Someone is already working to solve this problem? How could I help solve it?

**Comment by norkans7** [comment]
@teehamaral You can open a PR with the changes to address this

**Comment by teehamaral** [comment]
Ok @norkans7, I will.
