### ISSUE TITLE
Update the results of polls

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/ureport#201]
It is happening when the category changes in flow in the RapidPro, the results of the "old" category be forgotten and start counting from the new. This is normal?

**Comment by nicpottier** [comment]
Yes, as we don't know that those categories are equivelant in any way.

**Comment by johncordeiro** [comment]
What is happening is that the category name is being considered as the key response, if we change  this key to rule uuid it could work better. What do you think about it?
