### ISSUE TITLE
Different age graphic display

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/ureport#211]
The age chart is displayed differently in different pages. On the home page it is displayed with divergent data, since the U-Reporters page shows exactly the opposite of the homepage. This happens when we use the Arabic language (see screenshots).

Home page:
![Home page](https://cloud.githubusercontent.com/assets/5198870/18435764/77ddb47e-78cb-11e6-9843-78b49ee54e34.png)

U-Reporters page:
![U-Reporters page](https://cloud.githubusercontent.com/assets/5198870/18435793/94a554d6-78cb-11e6-985e-fba3760f6e12.png)

**Comment by norkans7** [comment]
Thanks to report this @teehamaral 

A fix is added in https://github.com/rapidpro/ureport/pull/212/commits/ff53eb7052e47704f3904b19cd43617dfe1d9dd2
