### ISSUE TITLE
Cutting the chart description when displayed in Arabic

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/ureport#221]
We note that in some cases the chart title, depending on the amount of characters, is cut only when it is used the Arabic language, see the following screenshot:
 
![screen shot 2016-10-10 at 09 36 39](https://cloud.githubusercontent.com/assets/5198870/19236410/9670d46c-8ecd-11e6-9018-4e3b39ed7a12.png)

**Comment by norkans7** [comment]
FIxed in #227
