### ISSUE TITLE
Error on categories display when RTL language

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/ureport#247]
Current:
![screen shot 2016-11-16 at 15 09 01](https://cloud.githubusercontent.com/assets/5198870/20359536/1828fa6c-ac0f-11e6-843a-3704e6a5a371.png)

How it should be:
![screen shot 2016-11-16 at 15 11 51](https://cloud.githubusercontent.com/assets/5198870/20359538/1c776c8e-ac0f-11e6-8822-ad761f2d130c.png)

**Comment by norkans7** [comment]
not clear to me the difference may be it'll be more clear with a PR
