### ISSUE TITLE
Stories display 

### ISSUE THREAD

**Issue by nelsonlapf** [rapidpro/ureport#288]
Hi guys,

Today the guys from Brazil asked us to hide the stories from the home page, however, it´s not possible unless if I remove them from the whole site, even from the story tab. 

When I uncheck the box "Is featured" in my opinion, the story should be "removed" from the home page and should continue to be displayed on the story tab, however, it´s the opposite when I unselect the box, the story is removed only from the story tab and still available on the home page. 

What do you think about this?

**Comment by norkans7** [comment]
That makes sense as we changed to display the stories on the homepage the same way whether featured or not.

**Comment by nelsonlapf** [comment]
that´s the point, I think that would better if we only display stories on the homepage only if it was set as featured and if it´s not, only be displayed on the stories tab.

**Comment by norkans7** [comment]
Sure I agree we can remove the stories that are not featured to be shown on the homepage.
Please open a PR with those changes
