### ISSUE TITLE
Importing Data with date 

### ISSUE THREAD

**Issue by nelsonlapf** [rapidpro/ureport#292]
Hi guys,

I was trying to import an excel file with a date on it (DD/MM/YYYY) as set in the organization, however, the system does not accept this configuration, and only accepts the American format (MM/DD/YYYY).

I think that it should take the org configuration instead of having a standard for it, here in Brazil we do not use (MM/DD) and will be hard to ask our users to always change this before uploading a file.

Can we make it happen?

**Comment by norkans7** [comment]
I do not think users should get to the polls import they should be using the create view instead,
why would a user prefer importing instead of the create view?

**Comment by nelsonlapf** [comment]
It´s not the poll, but the contact list for example.

**Comment by nelsonlapf** [comment]
If you already have a list of contacts with the birthday (example), we will need to adjust it to American format every time before import.

**Comment by norkans7** [comment]
U-Report is supposed to get all the data from RapidPro so it does not make sense to import contacts

**Comment by nelsonlapf** [comment]
sorry, wrong repository. My mistake.
