### ISSUE TITLE
Alpha Issues

### ISSUE THREAD

**Issue by nicpottier** [rapidpro/ureport#453]
Just starting a monster issue to track things that need doing:
- [x] video on homepage needs to be country specific
- [x] should use block (or config value) for join message
- [x] use block for engagement page
- [x] use block for photos title / content
- [x] use blocks for join steps
- [x] use block or config for engagement callout on bottom
- [x] use block or config for opinions header
- [x] use block or config for join header
- [x] use block or config for stories header
- [x] faq page needs max width treatment
- [x] jobs page needs max width treatment
- [x] scale font size on index poll, poll page, questions and story titles based on length
- [x] another go at left angle on homepage
- [x] change engagement page top to be all time stats
- [x] engagement stats precalculated (say at midnight) and cached for 24 hours so we never have cache misses
- [x] search styling
- [x] search jumping on click
- [x] search via year / month
- [x] reduce GIANT circle numbers
- [x] full theme colors

**Comment by norkans7** [comment]
Added homepage video config in https://github.com/rapidpro/ureport/pull/456/commits/13edc268e5814b3567f12a17b04b5a6df4370201

**Comment by norkans7** [comment]
I think join message can use the existing `{{org|config:"join_text"}}`

**Comment by norkans7** [comment]
Reused she existing blocks for join steps and join header in https://github.com/rapidpro/ureport/pull/456/commits/799535b3b6d0d3e46d4e4a38123e828ba3b179d8

**Comment by norkans7** [comment]
Added photos section config values in https://github.com/rapidpro/ureport/pull/456/commits/a0bfe1bcc4a6bc2be57c5ab096067b0789696808

**Comment by norkans7** [comment]
Added  more description config values for stories header, polls header, engagement header and the footer engagement callout message in https://github.com/rapidpro/ureport/pull/456/commits/fca8f04620b828266e3305fd71ab0f9a9aaf5a6c

**Comment by norkans7** [comment]
I am not sure if "another go at left angle on homepage" is the oblique clip on the homepage but if it is I think I have it right finally(both desktop and mobile) in https://github.com/rapidpro/ureport/pull/454/commits/d89f8bc3c103ce3e3bc6948ac36e2b324fa06059

**Comment by nicpottier** [comment]
Nice, ya I was more talking about the left side of that angle, but I think that's extra credit anyways.

**Comment by nicpottier** [comment]
Join message is already a config isn't it? Thought I saw it when in there. If you just tweak the font size (just one step down when more than 50 chars) then I think we can merge all this stuff and ship.

**Comment by norkans7** [comment]
Add font size reduction for longer texts in https://github.com/rapidpro/ureport/pull/457/commits/d847cfa767eae772efbb91a595522a8b7df50956

**Comment by norkans7** [comment]
Reused the join text in https://github.com/rapidpro/ureport/pull/457/commits/87fdab80825ba385a92117601d53199ea44e946f and fixed the left homepage in https://github.com/rapidpro/ureport/pull/457/commits/87be52febcca13a9405ef9fa344eabb396fbee07

**Comment by nicpottier** [comment]
Is the text in the left box still vertically aligned with the text in the box below?

**Comment by norkans7** [comment]
Nope, if that is required, then that is broken, I'lll have to work on that again

**Comment by norkans7** [comment]
That should be addressed too in https://github.com/rapidpro/ureport/commit/e324991426abff1cfe6bb3e1bd872e8494b6bc90
