### ISSUE TITLE
Add Viber on U-Report

### ISSUE THREAD

**Issue by matmsa27** [rapidpro/ureport#576]
Hi everyone, I want to discuss the possibility to add Viber configurations on U-Report. Bulgaria UReport needs to use Viber because Viber on their country is more used than other social networks. 

I want raise the impact to implement this, and how to implement this.

I studied the code, and I got it some points to implement.

1 - Add Viber fields on org_config_fields defined on settings
2 - Configure templates to support Viber fields. The templates to configure are:
* `base_admin_dashboard.haml`
* `frame.haml`
* `public_base.haml`

There are many points to do beyond these?

Thanks for help and attention.

Regards.

**Comment by norkans7** [comment]
The main thing here really is how do you display that where is that supposed to be show to the public and how?
What are the interaction? does viber have a link to conversation like whatsapp(https://faq.whatsapp.com/en/android/26000030/)?

**Comment by matmsa27** [comment]
Hi @norkans7 , sorry for the delay.

Yes, the Viber supports the link to a conversation like WhatsApp example that you mentioned. It can be found [here](https://developers.viber.com/docs/tools/deep-links/#deep-links).

There is a way for the Viber icon shows beside the twitter, or Instagram icon like the images below?
![Clipboard - 8 de Abril de 2020 às 08_21](https://user-images.githubusercontent.com/10725273/78899933-7f4bd200-7a4c-11ea-95f8-ca9d1dda5bfc.png)

Another question is if can we implement the widget for Viber conversation like Facebook message?

![Clipboard - 8 de Abril de 2020 às 08_28](https://user-images.githubusercontent.com/10725273/78900201-e23d6900-7a4c-11ea-9e6a-f806e5c1fe1d.png)

Do you see another place to put the Viber configuration on templates?

Thanks, Norkans.
Regards.

**Comment by norkans7** [comment]
I think Viber can only be added on the join page http://ureport.in/join/ using the deep link

I think it is not useful as a social media icon and also I am not sure we want another widget like Facebook messenger

For the join page you can open a PR and submit a screenshot for a case of all possible channel configured are available and configured

**Comment by matmsa27** [comment]
Nice, I got it.

There a way and possibility to put on the place following the image below? On the up right corner, and the downright corner.

![Screenshot from 2020-04-09 12-20-08](https://user-images.githubusercontent.com/10725273/78911296-837feb80-7a5c-11ea-80cb-5995bad78065.png)

Thanks Norkans.

**Comment by norkans7** [comment]
No, that is not an option, those are social media

Viber is a channel just like WhatsApp the only place they can be added in the join page

**Comment by nicpottier** [comment]
Does Viber have a widget like Facebook for chat?

**Comment by matmsa27** [comment]
Floating chat widget for Viber officially like Facebook doesn't exists, only unofficially, but I believe it's not recommended to use, according to that Viber doesn't provide support.

Ok, we will implement to put Viber on the join page. PR cooming soon.
