### ISSUE TITLE
Logging in with invalid credentials fails without returning an error on the UI

### ISSUE THREAD

**Issue by evansmurithi** [rapidpro/ureport#674]
Entering wrong credentials on the login page returns an error that is not visible unless highlighted as shown below. The classes `.alert` and `.alert-danger` have been defined in the bootstrap.css file which has not been linked in the `templates/frame.haml` file.
 
![](https://user-images.githubusercontent.com/20133492/107338562-bb1c5180-6acc-11eb-81be-a5000355e894.png)

**Comment by norkans7** [comment]
That page uses Bulma CSS so I added the right CSS classes 

Fixed in https://github.com/rapidpro/ureport/pull/675/

<img width="924" alt="U-Report 2021-02-09 18-43-32" src="https://user-images.githubusercontent.com/1040571/107396829-cbe9b900-6b06-11eb-888d-8c6fd65ef8d8.png">
