### ISSUE TITLE
Wrong invitation link sent to users

### ISSUE THREAD

**Issue by evansmurithi** [rapidpro/ureport#700]
When inviting users to an organization, the users receive an invitation link that does not have the subdomain. Users receive invitation link as `http://domain.com/join_url` instead of `https://subdomain.domain.com/join_url`

References this issue https://github.com/rapidpro/dash/issues/122

**Comment by norkans7** [comment]
There are some misconfiguration on and more details are on https://github.com/rapidpro/dash/issues/122#issuecomment-822391147
