### ISSUE TITLE
Trying to add New Poll gives API Token configuration error

### ISSUE THREAD

**Issue by redwanalvi** [rapidpro/ureport#842]
Hello!

I have set up a U-Report development environment in my local machine, and am trying to create a new poll for my dummy org. However, I always seem to get hit with **"Your org does not have any API token configuration."** Where can I actually configure this. There is no option to provide an API Token when creating an org.

At this point I should also mention that I have a rapidpro instance running on localhost in port 8001. There is an API Token available from rapidpro, but I am unsure how and where to add this in my U-Report instance. Or whether I am supposed to add it to U-Report in the first place?

Now, this might be a rudimentary issue, but I cannot find a solution to this anywhere, which may suggest people do not run into this problem very often. And that is precisely why I am at my wits end. Am I missing something here? How can I configure API Token for my org in order to create and carry out polls? Could you possibly point me to the right direction regarding this?

Thanks in advance!

**Comment by nelsonfrank** [comment]
did you manage to resolve this @redwanalvi ?
If yes, how did you do it?

I will appreciate any suggestion, Thanks in advance

**Comment by redwanalvi** [comment]
Oh boy it has been a while since I last visited it!

As a superuser, go to /manage/org/home/  (just put it in the URL bar if you can't find a way to get that).

There, you should find the "Backends" option where you should be able to configure the API token as well as add the field to point to your rapidpro instance.

Hope that helps!

**Comment by nelsonfrank** [comment]
Thanks in advance, I manage to configure it. 
Maybe i will update some of this repo documentation.
