### ISSUE TITLE
Polls are not syncing

### ISSUE THREAD

**Issue by alviriseup** [rapidpro/ureport#844]
Hello!

I have a U-Report test server configured in my local machine, and I have come across an issue regarding polls syncing. The polls are created without a hitch; however, once the polls are created, it keeps showing that poll syncing is in progress 0.0%.

![Screenshot from 2021-12-13 18-01-30](https://user-images.githubusercontent.com/95750048/145808674-d9e09dba-2079-4802-94a2-5df13cdb4828.png)

The flow_uuid needed for the polls is coming from a rapidpro instance I have running on `localhost:8001`. After diving in deeper into the issue, I found that U-Report does not seem to even update any new flows I might create in my rapidpro server. It only takes the flows that already exist at the time of configuring the API Token for the org in the backend, and that's it. Any new flows created in the rapidpro server after that point does not seem to register in U-Report when creating a new poll.

At first I thought it might have been because of version differences (I was running rapidpro v6.4.8). But the problem persists even after updating rapidpro to the latest v7.0.4 stable release. Checking for polls using API endpoints also gives `"count" = 0`.

![Screenshot from 2021-12-13 18-32-19](https://user-images.githubusercontent.com/95750048/145812801-c4f6b822-0184-42f4-b6e9-cb8f446d874e.png)

It seems to me that there might be some issues with the connection between my U-Report dashboard and the rapidpro instance. But I cannot quite put my finger on it. 

What am I missing to make the poll syncing work?

**Comment by norkans7** [comment]
The poll sync happens in the background tasks, you need to be running celery for that to work.
And you need 3 celery queues `celery`, `sync` and `slow` for every task to run

**Comment by alviriseup** [comment]
Hello @norkans7 , thank you for your response. It did the trick in solving the polls not syncing issue! 
However, one problem that persists is the flow list not updating new flows from radpidpro. I have created a few new Flows in the rapidpro instance, but those are not available in U-Report dashboard. It only shows the flows that existed at the time of configuring the Org backend. I am referring to the section where we have to select the flow-uuid when creating a new poll in U-Report.
Could you advise on how this problem can be solved?

**Comment by norkans7** [comment]
there is task for that that should run regularly https://github.com/rapidpro/ureport/blob/de8b5cd7233d66d051661e59f5f22807373a8f12/ureport/settings_common.py#L879

make sure you run celery beat

You'll need to investigate more on your setup

**Comment by alviriseup** [comment]
Sure, that sounds reasonable.  I had a feeling there was something missing on my end. Have not run into celery beat, and I guess that was the missing component. I'll investigate further into my setup and will get back if the problem still persists.

**Comment by alviriseup** [comment]
The steps mentioned above solved the issues, everything runs perfectly now. Thank you!
