### ISSUE TITLE
Adding all Org config fields to the edit org form form

### ISSUE THREAD

**Issue by xkmato** [rapidpro/ureport#96]
A couple of configs like `[reporter_group, born_label, gender_label, occupation_label, registration_label, state_label, district_label, male_label, female_label]` are not of the edit org form `/manage/org/edit/`. Since there is also no documentation on this, this makes it quite hard for someone new to start up a ureport.

Although all the required fields are listed in `ureport/settings_common.py` as `ORG_CONFIG_FIELD`. I am wondering if there is any specific reason why these are not on that form, and if none, should I add them?

**Comment by norkans7** [comment]
Org is a model in Dash which is used in many projects with different requirements, 

Org has the common fields to all projects and on each project we use ORG_CONFIG_FIELDS in settings to declare other specific fields to the particular project.

I do not think you need to add those field on the Edit view, they are derived from the settings https://github.com/rapidpro/dash/blob/master/dash/orgs/views.py#L238

**Comment by xkmato** [comment]
Nice, I missed that. We just need to have these documented somewhere.
